# Generated by Django 6.0.5 on 2026-08-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0002_modelolaptopcomponente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionCompatibilidadComponente',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estacion_compatibilidad_componente',
                'managed': False,
            },
        ),
    ]
